/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent() {
  return (
    <div className="flex flex-col items-center pb-20 max-w-xs text-xl text-center text-black bg-zinc-100">
      <div className="flex flex-col justify-center self-stretch w-full text-2xl font-semibold text-neutral-400">
        <div className="flex gap-5 justify-between bg-white">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/654f5eb8d36b69a7bc8a238a4383f2c8cc06a837180233bda8116662947ba4c2?apiKey=5945b86f73654742be8e9fc146e85854&"
            className="shrink-0 my-auto w-10 aspect-square"
          />
          <div className="flex gap-5 px-5">
            <div className="flex-auto my-auto">Mina favoriter</div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/096face5ae65e68dc9e3a004b6de928377e67343b360f60bc5e0ba8314ca7595?apiKey=5945b86f73654742be8e9fc146e85854&"
              className="shrink-0 aspect-square w-[60px]"
            />
          </div>
        </div>
      </div>
      <div className="mt-8 w-full text-2xl font-semibold">
        Hur vill du lägga till aktiviteter?
      </div>
      <div className="flex flex-col justify-center mt-8 w-full max-w-[250px]">
        <div className="justify-center items-center px-16 py-5 bg-white rounded-xl border border-solid shadow-sm border-neutral-700">
          Välj från lista
        </div>
      </div>
      <div className="flex flex-col justify-center mt-10 w-full max-w-[250px]">
        <div className="justify-center px-7 py-5 bg-white rounded-xl border border-solid shadow-sm border-neutral-700">
          Se en aktivitet i taget
        </div>
      </div>
      <div className="flex flex-col justify-center mt-10 w-full max-w-[250px]">
        <div className="justify-center px-4 py-5 bg-white rounded-xl border border-solid shadow-sm border-neutral-700">
          Skapa en egen aktivitet
        </div>
      </div>
    </div>
  );
}

export default MyComponent; //Hjälper om den kör sig själv, lol
