/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

interface ButtonProps {
  children: React.ReactNode;
  className?: string;
}

const Button: React.FC<ButtonProps> = ({ children, className }) => {
  return (
    <div className={`flex flex-col justify-center w-full max-w-[250px] ${className}`}>
      <div className="justify-center px-4 py-5 bg-white rounded-xl border border-solid shadow-sm border-neutral-700">
        {children}
      </div>
    </div>
  );
};

const buttons = [
  { id: 1, text: "Välj från lista" },
  { id: 2, text: "Se en aktivitet i taget" },
  { id: 3, text: "Skapa en egen aktivitet" },
];

const MyComponent: React.FC = () => {
  return (
    <div className="flex flex-col items-center pb-20 max-w-xs text-xl text-center text-black bg-zinc-100">
      <header className="flex flex-col justify-center self-stretch w-full text-2xl font-semibold text-neutral-400">
        <div className="flex gap-5 justify-between bg-white">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/48467c071e560511179c0a314b0c24dfc34dccb5535bccc316c9622f5c2d4931?apiKey=4335baeda03e4ce8ad5618062684a1a3&"
            alt="Placeholder"
            className="shrink-0 my-auto w-10 aspect-square"
          />
          <div className="flex gap-5 px-5">
            <h1 className="flex-auto my-auto">Mina favoriter</h1>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/096face5ae65e68dc9e3a004b6de928377e67343b360f60bc5e0ba8314ca7595?apiKey=4335baeda03e4ce8ad5618062684a1a3&"
              alt="Placeholder"
              className="shrink-0 aspect-square w-[60px]"
            />
          </div>
        </div>
      </header>
      <h2 className="mt-8 w-full text-2xl font-semibold">
        Hur vill du lägga till aktiviteter?
      </h2>
      <nav>
        {buttons.map((button) => (
          <Button key={button.id} className={`mt-${button.id === 1 ? 8 : 10}`}>
            {button.text}
          </Button>
        ))}
      </nav>
    </div>
  );
};

export default MyComponent;