/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent() {
  return (
    <div className="flex flex-col items-center pb-4 max-w-xs bg-zinc-100">
      <div className="flex gap-4 justify-center self-stretch p-2 text-2xl font-bold text-center bg-white border-b border-black border-solid text-neutral-700">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/ec1cc0cbcf893b45a7c8f716945c83050335c636bb9f6cedcd89d11d91e36871?apiKey=5945b86f73654742be8e9fc146e85854&"
          className="shrink-0 w-14 aspect-square"
        />
        <div className="my-auto">Mina favoriter</div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/d07566d0de959d6f64473b99a970127a8d2510dfa7b20e7148b20eaa680481d6?apiKey=5945b86f73654742be8e9fc146e85854&"
          className="shrink-0 w-14 aspect-square"
        />
      </div>
      <div className="mt-4 text-xl font-semibold text-center text-black">
        Vill du lägga till denna aktivitet?
      </div>
      <div className="flex flex-col items-center px-9 py-4 mt-4 w-full bg-white rounded-xl border border-black border-solid shadow-sm max-w-[288px]">
        <div className="text-lg font-medium text-black">Hopprep</div>
        <img
          loading="lazy"
          srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/9d8a188425f478a2d7ebd982637b9dd4ba6aefd7afa4cecf6b8bd335560180dd?apiKey=5945b86f73654742be8e9fc146e85854&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/9d8a188425f478a2d7ebd982637b9dd4ba6aefd7afa4cecf6b8bd335560180dd?apiKey=5945b86f73654742be8e9fc146e85854&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/9d8a188425f478a2d7ebd982637b9dd4ba6aefd7afa4cecf6b8bd335560180dd?apiKey=5945b86f73654742be8e9fc146e85854&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/9d8a188425f478a2d7ebd982637b9dd4ba6aefd7afa4cecf6b8bd335560180dd?apiKey=5945b86f73654742be8e9fc146e85854&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/9d8a188425f478a2d7ebd982637b9dd4ba6aefd7afa4cecf6b8bd335560180dd?apiKey=5945b86f73654742be8e9fc146e85854&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/9d8a188425f478a2d7ebd982637b9dd4ba6aefd7afa4cecf6b8bd335560180dd?apiKey=5945b86f73654742be8e9fc146e85854&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/9d8a188425f478a2d7ebd982637b9dd4ba6aefd7afa4cecf6b8bd335560180dd?apiKey=5945b86f73654742be8e9fc146e85854&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/9d8a188425f478a2d7ebd982637b9dd4ba6aefd7afa4cecf6b8bd335560180dd?apiKey=5945b86f73654742be8e9fc146e85854&"
          className="mt-3 w-full aspect-square"
        />
        <div className="justify-center px-4 py-3 mt-3 text-base text-black bg-white rounded-xl border border-black border-solid shadow-sm">
          Se beskrivning
        </div>
      </div>
      <div className="flex gap-5 justify-between mt-4 w-full text-lg text-black max-w-[288px]">
        <div className="justify-center p-4 bg-white rounded-xl border border-black border-solid shadow-sm">
          Nej, inte den
        </div>
        <div className="justify-center p-4 bg-white rounded-xl border border-black border-solid shadow-sm">
          Ja, lägg till
        </div>
      </div>
    </div>
  );
}

export default MyComponent; //Hjälper om den kör sig själv, lol
