/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

interface ButtonProps {
  children: React.ReactNode;
  className?: string;
}

const Button: React.FC<ButtonProps> = ({ children, className }) => {
  return (
    <button className={`justify-center p-4 bg-white rounded-xl border border-black border-solid shadow-sm ${className}`}>
      {children}
    </button>
  );
};

interface ImageCardProps {
  src: string;
  title: string;
}

const ImageCard: React.FC<ImageCardProps> = ({ src, title }) => {
  return (
    <div className="flex flex-col items-center px-9 py-4 mt-4 w-full bg-white rounded-xl border border-black border-solid shadow-sm max-w-[288px]">
      <div className="text-lg font-medium text-black">{title}</div>
      <img src={src} alt={title} className="mt-3 w-full aspect-square" />
      <button className="justify-center px-4 py-3 mt-3 text-base text-black bg-white rounded-xl border border-black border-solid shadow-sm">
        Se beskrivning
      </button>
    </div>
  );
};

function MyComponent() {
  const images = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/d0092a212cf31bdbae1f0a5a93d16583b31530c8f66c5aa2aa0a9cb72c02ba3c?apiKey=4335baeda03e4ce8ad5618062684a1a3&",
      alt: "Left icon",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/4143c65dbe18887cde2baa9486b1264544c76ae525a30b32ca2e056d4ff9f9b0?apiKey=4335baeda03e4ce8ad5618062684a1a3&",
      alt: "Right icon",
    },
  ];

  return (
    <div className="flex flex-col items-center pb-4 max-w-xs bg-zinc-100">
      <header className="flex gap-4 justify-center self-stretch p-2 text-2xl font-bold text-center bg-white border-b border-black border-solid text-neutral-700">
        {images.map((image, index) => (
          <img
            key={index}
            src={image.src}
            alt={image.alt}
            className="shrink-0 w-14 aspect-square"
          />
        ))}
        <h1 className="my-auto">Mina favoriter</h1>
      </header>
      <main>
        <h2 className="mt-4 text-xl font-semibold text-center text-black">
          Vill du lägga till denna aktivitet?
        </h2>
        <ImageCard src="https://cdn.builder.io/api/v1/image/assets/TEMP/9d8a188425f478a2d7ebd982637b9dd4ba6aefd7afa4cecf6b8bd335560180dd?apiKey=4335baeda03e4ce8ad5618062684a1a3&" title="Hopprep" />
        <div className="flex gap-5 justify-between mt-4 w-full text-lg text-black max-w-[288px]">
          <Button>Nej, inte den</Button>
          <Button>Ja, lägg till</Button>
        </div>
      </main>
    </div>
  );
}

export default MyComponent;