/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

interface IconProps {
  src: string;
  alt: string;
  className?: string;
}

const Icon: React.FC<IconProps> = ({ src, alt, className }) => (
  <img loading="lazy" src={src} alt={alt} className={className} />
);

interface ButtonProps {
  children: React.ReactNode;
  className?: string;
}

const Button: React.FC<ButtonProps> = ({ children, className }) => (
  <div className={`justify-center px-2.5 py-3.5 bg-white rounded-xl border border-solid shadow-sm border-neutral-700 ${className}`}>
    {children}
  </div>
);

const MyComponent: React.FC = () => {
  const favorites = [
    {
      id: 1,
      title: "Cykla",
      image: "https://cdn.builder.io/api/v1/image/assets/TEMP/67d528dec156f2e7793fd1237c0df4bf00fff9920694d5e75ba23f2a41ff524f?apiKey=4335baeda03e4ce8ad5618062684a1a3&",
    },
  ];

  return (
    <div className="flex flex-col justify-center max-w-xs text-center text-black bg-zinc-100">
      <div className="flex flex-col px-5 pb-6 w-full bg-zinc-100">
        <header className="flex flex-col justify-center w-full text-2xl font-semibold text-neutral-400">
          <div className="flex gap-5 justify-between bg-white">
            <Icon src="https://cdn.builder.io/api/v1/image/assets/TEMP/48467c071e560511179c0a314b0c24dfc34dccb5535bccc316c9622f5c2d4931?apiKey=4335baeda03e4ce8ad5618062684a1a3&" alt="Icon 1" className="shrink-0 my-auto w-10 aspect-square" />
            <div className="flex gap-5">
              <h1 className="flex-auto my-auto">Mina favoriter</h1>
              <Icon src="https://cdn.builder.io/api/v1/image/assets/TEMP/096face5ae65e68dc9e3a004b6de928377e67343b360f60bc5e0ba8314ca7595?apiKey=4335baeda03e4ce8ad5618062684a1a3&" alt="Icon 2" className="shrink-0 aspect-square w-[60px]" />
            </div>
          </div>
        </header>
        <h2 className="mt-3 w-full text-xl font-medium">
          Vill du lägga till denna aktivitet?
        </h2>
        <section className="flex flex-col justify-center self-center mt-2.5">
          {favorites.map((favorite) => (
            <article key={favorite.id} className="flex flex-col items-center px-6 py-5 bg-white rounded-xl border border-black border-solid shadow-sm">
              <h3 className="text-2xl font-medium">{favorite.title}</h3>
              <Icon src={favorite.image} alt={`${favorite.title} image`} className="self-stretch mt-4 w-full aspect-square" />
              <div className="flex flex-col justify-center mt-5 max-w-full text-base w-[130px]">
                <Button>Se beskrivning</Button>
              </div>
            </article>
          ))}
        </section>
        <div className="flex gap-5 self-center mt-6 text-xl">
          <div className="flex flex-col flex-1 justify-center">
            <Button className="px-2 py-5">Nej, inte den</Button>
          </div>
          <div className="flex flex-col flex-1 justify-center">
            <Button className="px-4 py-5">Ja, lägg till</Button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default MyComponent;