/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

interface ButtonProps {
  children: React.ReactNode;
  className?: string;
}

const Button: React.FC<ButtonProps> = ({ children, className }) => {
  return (
    <button className={`justify-center px-4 py-3 text-base text-black bg-white rounded-xl border border-black border-solid shadow-sm ${className}`}>
      {children}
    </button>
  );
};

interface ImageCardProps {
  title: string;
  imageUrl: string;
}

const ImageCard: React.FC<ImageCardProps> = ({ title, imageUrl }) => {
  return (
    <div className="flex flex-col items-center px-9 py-4 mt-4 w-full bg-white rounded-xl border border-black border-solid shadow-sm max-w-[288px]">
      <div className="text-lg font-medium text-black">{title}</div>
      <img src={imageUrl} alt={title} className="mt-3 w-full aspect-square" />
      <Button>Se beskrivning</Button>
    </div>
  );
};

const MyComponent: React.FC = () => {
  const imageCards = [
    {
      title: "Cykla",
      imageUrl: "https://cdn.builder.io/api/v1/image/assets/TEMP/868ecd849b4b76ea78634a04815013581a0cc62849005fb56781b94d7610c7e6?apiKey=4335baeda03e4ce8ad5618062684a1a3&",
    },
  ];

  return (
    <div className="flex flex-col items-center pb-4 max-w-xs bg-zinc-100">
      <header className="flex gap-4 justify-center self-stretch p-2 text-2xl font-bold text-center bg-white border-b border-black border-solid text-neutral-700">
        <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/d0092a212cf31bdbae1f0a5a93d16583b31530c8f66c5aa2aa0a9cb72c02ba3c?apiKey=4335baeda03e4ce8ad5618062684a1a3&" alt="" className="shrink-0 w-14 aspect-square" />
        <h1 className="my-auto">Mina favoriter</h1>
        <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/34de480f78d298e70ed1470d588a444fdbc4638545c4d7f4910b7599e2938954?apiKey=4335baeda03e4ce8ad5618062684a1a3&" alt="" className="shrink-0 w-14 aspect-square" />
      </header>
      <main>
        <h2 className="mt-4 text-xl font-semibold text-center text-black">
          Vill du lägga till denna aktivitet?
        </h2>
        {imageCards.map((card, index) => (
          <ImageCard key={index} title={card.title} imageUrl={card.imageUrl} />
        ))}
        <div className="flex gap-5 justify-between mt-4 w-full text-lg text-black max-w-[288px]">
          <Button>Nej, inte den</Button>
          <Button>Ja, lägg till</Button>
        </div>
      </main>
    </div>
  );
};

export default MyComponent;