/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

interface HeaderProps {
  title: string;
  icon: string;
  image: string;
}

const Header: React.FC<HeaderProps> = ({ title, icon, image }) => {
  return (
    <header className="flex gap-5 justify-between bg-white">
      <img loading="lazy" src={icon} alt="" className="shrink-0 my-auto w-10 aspect-square" />
      <div className="flex gap-5">
        <h1 className="flex-auto my-auto">{title}</h1>
        <img loading="lazy" src={image} alt="" className="shrink-0 aspect-square w-[60px]" />
      </div>
    </header>
  );
};

interface ActivityCardProps {
  title: string;
  image: string;
}

const ActivityCard: React.FC<ActivityCardProps> = ({ title, image }) => {
  return (
    <div className="flex flex-col items-center px-6 py-5 bg-white rounded-xl border border-black border-solid shadow-sm">
      <h2 className="text-2xl font-medium">{title}</h2>
      <img loading="lazy" src={image} alt={title} className="self-stretch mt-4 w-full aspect-square" />
      <div className="flex flex-col justify-center mt-5 max-w-full text-base w-[130px]">
        <button className="justify-center px-2.5 py-3.5 bg-white rounded-xl border border-solid shadow-sm border-neutral-700">
          Se beskrivning
        </button>
      </div>
    </div>
  );
};

interface ButtonProps {
  children: React.ReactNode;
  onClick: () => void;
}

const Button: React.FC<ButtonProps> = ({ children, onClick }) => {
  return (
    <div className="flex flex-col flex-1 justify-center">
      <button
        className="justify-center px-4 py-5 bg-white rounded-xl border border-solid shadow-sm border-neutral-700"
        onClick={onClick}
      >
        {children}
      </button>
    </div>
  );
};

function MyComponent() {
  return (
    <div className="flex flex-col justify-center max-w-xs text-center text-black bg-zinc-100">
      <div className="flex flex-col px-5 pb-6 w-full bg-zinc-100">
        <div className="flex flex-col justify-center w-full text-2xl font-semibold text-neutral-400">
          <Header title="Mina favoriter" icon="https://cdn.builder.io/api/v1/image/assets/TEMP/48467c071e560511179c0a314b0c24dfc34dccb5535bccc316c9622f5c2d4931?apiKey=4335baeda03e4ce8ad5618062684a1a3&" image="https://cdn.builder.io/api/v1/image/assets/TEMP/096face5ae65e68dc9e3a004b6de928377e67343b360f60bc5e0ba8314ca7595?apiKey=4335baeda03e4ce8ad5618062684a1a3&" />
        </div>
        <h2 className="mt-3 w-full text-xl font-medium">Vill du lägga till denna aktivitet?</h2>
        <div className="flex flex-col justify-center self-center mt-2.5">
          <ActivityCard title="Hoppa hopprep" image="https://cdn.builder.io/api/v1/image/assets/TEMP/4203b3f852cb0ba5fe95c3b652029eddc4cccc60fd1df722dd715590e5d9d1e8?apiKey=4335baeda03e4ce8ad5618062684a1a3&" />
        </div>
        <div className="flex gap-5 self-center mt-6 text-xl">
          <Button onClick={() => console.log("Nej, inte den")}>Nej, inte den</Button>
          <Button onClick={() => console.log("Ja, lägg till")}>Ja, lägg till</Button>
        </div>
      </div>
    </div>
  );
}

export default MyComponent;