/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent() {
  return (
    <div className="flex flex-col justify-center max-w-xs text-center text-black bg-zinc-100">
      <div className="flex flex-col px-5 pb-6 w-full bg-zinc-100">
        <div className="flex flex-col justify-center w-full text-2xl font-semibold text-neutral-400">
          <div className="flex gap-5 justify-between bg-white">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/654f5eb8d36b69a7bc8a238a4383f2c8cc06a837180233bda8116662947ba4c2?apiKey=5945b86f73654742be8e9fc146e85854&"
              className="shrink-0 my-auto w-10 aspect-square"
            />
            <div className="flex gap-5">
              <div className="flex-auto my-auto">Mina favoriter</div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/096face5ae65e68dc9e3a004b6de928377e67343b360f60bc5e0ba8314ca7595?apiKey=5945b86f73654742be8e9fc146e85854&"
                className="shrink-0 aspect-square w-[60px]"
              />
            </div>
          </div>
        </div>
        <div className="mt-3 w-full text-xl font-medium">
          Vill du lägga till denna aktivitet?
        </div>
        <div className="flex flex-col justify-center self-center mt-2.5">
          <div className="flex flex-col items-center px-6 py-5 bg-white rounded-xl border border-black border-solid shadow-sm">
            <div className="text-2xl font-medium">Cykla</div>
            <img
              loading="lazy"
              srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/67d528dec156f2e7793fd1237c0df4bf00fff9920694d5e75ba23f2a41ff524f?apiKey=5945b86f73654742be8e9fc146e85854&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/67d528dec156f2e7793fd1237c0df4bf00fff9920694d5e75ba23f2a41ff524f?apiKey=5945b86f73654742be8e9fc146e85854&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/67d528dec156f2e7793fd1237c0df4bf00fff9920694d5e75ba23f2a41ff524f?apiKey=5945b86f73654742be8e9fc146e85854&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/67d528dec156f2e7793fd1237c0df4bf00fff9920694d5e75ba23f2a41ff524f?apiKey=5945b86f73654742be8e9fc146e85854&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/67d528dec156f2e7793fd1237c0df4bf00fff9920694d5e75ba23f2a41ff524f?apiKey=5945b86f73654742be8e9fc146e85854&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/67d528dec156f2e7793fd1237c0df4bf00fff9920694d5e75ba23f2a41ff524f?apiKey=5945b86f73654742be8e9fc146e85854&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/67d528dec156f2e7793fd1237c0df4bf00fff9920694d5e75ba23f2a41ff524f?apiKey=5945b86f73654742be8e9fc146e85854&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/67d528dec156f2e7793fd1237c0df4bf00fff9920694d5e75ba23f2a41ff524f?apiKey=5945b86f73654742be8e9fc146e85854&"
              className="self-stretch mt-4 w-full aspect-square"
            />
            <div className="flex flex-col justify-center mt-5 max-w-full text-base w-[130px]">
              <div className="justify-center px-2.5 py-3.5 bg-white rounded-xl border border-solid shadow-sm border-neutral-700">
                Se beskrivning
              </div>
            </div>
          </div>
        </div>
        <div className="flex gap-5 self-center mt-6 text-xl">
          <div className="flex flex-col flex-1 justify-center">
            <div className="justify-center px-2 py-5 bg-white rounded-xl border border-solid shadow-sm border-neutral-700">
              Nej, inte den
            </div>
          </div>
          <div className="flex flex-col flex-1 justify-center">
            <div className="justify-center px-4 py-5 bg-white rounded-xl border border-solid shadow-sm border-neutral-700">
              Ja, lägg till
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default MyComponent; //Hjälper om den kör sig själv, lol
