/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

interface ButtonProps {
  children: React.ReactNode;
}

const Button: React.FC<ButtonProps> = ({ children }) => {
  return (
    <button className="justify-center p-4 bg-white rounded-xl border border-black border-solid shadow-sm">
      {children}
    </button>
  );
};

const MyComponent: React.FC = () => {
  return (
    <div className="flex flex-col justify-center max-w-[290px]">
      <div className="flex flex-col px-5 pt-px pb-3.5 w-full rounded-xl border border-black border-solid shadow-sm bg-zinc-300">
        <div className="flex flex-col justify-center items-end px-16 w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/43bd3ee5d7415710a95d7a7a94367bdf19f5377c8a990c06090f129eddb3867e?apiKey=4335baeda03e4ce8ad5618062684a1a3&"
            alt="Decorative icon"
            className="w-14 aspect-square"
          />
        </div>
        <h2 className="mt-8 text-3xl font-semibold text-center text-black">
          Aktiviteten har lagts till i dina favoriter
        </h2>
        <div className="flex gap-4 justify-center mt-8 text-lg text-center text-black">
          <Button>Stäng väljaren</Button>
          <Button>Se nästa aktivitet</Button>
        </div>
      </div>
    </div>
  );
};

export default MyComponent;