/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

interface ButtonProps {
  onClick: () => void;
  children: React.ReactNode;
  className?: string;
}

const Button: React.FC<ButtonProps> = ({ onClick, children, className }) => {
  return (
    <button
      onClick={onClick}
      className={`justify-center px-6 py-3 bg-white rounded-xl border border-solid shadow-sm border-neutral-700 ${className}`}
    >
      {children}
    </button>
  );
};

const MyComponent: React.FC = () => {
  return (
    <div className="flex flex-col justify-center text-center text-black max-w-[286px]">
      <div className="flex flex-col px-5 pt-1.5 pb-10 w-full rounded-xl border border-black border-solid shadow-sm bg-zinc-300">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/17f12eb9f5e7ed790eabcc3c66b54ba9eeb06e6ebd581837a6b77e11a8dadd87?apiKey=4335baeda03e4ce8ad5618062684a1a3&"
          alt="Decorative image"
          className="self-end w-10 aspect-square"
        />
        <h2 className="self-center mt-8 w-full text-3xl font-semibold">
          Aktiviteten har lagts till i dina favoriter
        </h2>
        <div className="flex gap-2.5 self-start mt-16 text-xl">
          <div className="flex flex-col flex-1 justify-center">
            <Button
              onClick={() => {
                /* Handle close button click */
              }}
              className="px-7 py-2.5"
            >
              Stäng väljaren
            </Button>
          </div>
          <div className="flex flex-col flex-1 justify-center">
            <Button
              onClick={() => {
                /* Handle next activity button click */
              }}
            >
              Se nästa aktivitet
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default MyComponent;